dist: trusty
branches:
  only:
    - master
git:
  depth: 1
notifications:
  email:
    - arnab.k@gmail.com
language: node_js
node_js: "10.16.0"
before_script: yarn build
script:
  - git clone -b gh-pages https://github.com/arnabk/resume
  - cp -R ./build/* resume/
  - echo "BUILD_NUMBER ${BUILD_NUMBER} - web" > resume/build.details
  - yarn convert2pdf
  - mv resume.pdf resume/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: resume
  on:
    branch: master