git:
  depth: 1
language: node_js
matrix:
  fast_finish: true
node_js:
- 8.8.0
notifications:
  email:
  - arnab.k@gmail.com
branches:
  only:
  - master
before_install:
- npm install
install: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
env:
  global:
    secure: sd6CyDYzO4SLIheuk7cF2DQoltKotR4jMqVkrltD1JlSXewr2qMRej2zAW5xiAam2pzkcK3mDVJDZ4D/ECPppajqm9gOAfbO2qTk70YyAV2wMd7o57KTpag39CDRJsK93odbvg0gm3dNpuF+5vOdBxbSB0+BYRet5GtrwjiIPVz/QvKGGN4yspXS6U2CZ18dRN6x3Q5sSAXv9mYZVVidmj/lyJQtv17fsmovfkEobiGDX67inkRskVw1snSNUkssqJmiC0QoQMdYuWvvWTyd0xtA+6p1wLe+lVgX4JMUeW2QHKo/Thy6cfM4GSBc5brDb+mPNj/OToHCEijO21OvNbYLgCSGNn8YSiwaNQWSWiZJJJOCbtVWB/5HMjV60idCEuxeDb39f+ZAzatqqW0wD0bZhawaDF5EyPv2rkFNHwDS5J+Zba5DQm2OwdBUBmYbXzH0RqserjD3wK9Y6m8T70K9NPRMGf9aiVBGfXv+p7b/CbHd4FGoSVI5/qBWc1xwB52lmjJoyLIchuQsqIx0XaAotyo7mJRsmInBvkclyky3wMFUacPDK5Pybvshn83njgx4GtF9+99ACx5ywV5cr65emEZr2OHddOgrV8q1VRfbb3AW9u81DRMZWyd/XC40WnMMkWuCHfANB+mZGtFfDNK5SeCr4WiU/MjNxT9E0wQ=
