dist: trusty
branches:
  only:
    - master
git:
  depth: 1
notifications:
  email:
    - arnab.k@gmail.com
language: python
python: 3.6
script:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  - nvm use 10.16.0
  - npm i yarn -g
  - yarn
  - yarn build
  - git clone -b --depth=1 gh-pages https://github.com/arnabk/resume
  - cp -R ./build/* resume/
  - echo "BUILD_NUMBER ${BUILD_NUMBER} - web" > resume/build.details
  - yarn convert2pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: resume
  on:
    branch: master